### ISSUE TITLE
is:issue is:open Multi-class SMOTEBoost

### ISSUE THREAD

**Issue by arilwan** [dialnd/imbalanced-algorithms#2]
Just curious to ask, does this package supports a `multi-class` problem with a multi-minority scenario? Not sure if I read this correctly, but it seems to me the support is only for the `binary` class problem:
```
if minority_target is None:
    # Determine the minority class label.
    stats_c_ = Counter(y)
    maj_c_ = max(stats_c_, key=stats_c_.get)
    min_c_ = min(stats_c_, key=stats_c_.get)
    self.minority_target = min_c_
else:
    self.minority_target = minority_target
```

In my current task, I have a multi-majority multi-minority scenario:
```
Class = 0,	Count = 18749,	Percentage = 22.01
Class = 1,	Count = 3482,	Percentage = 4.09
Class = 2,	Count = 9566,	Percentage = 11.23
Class = 3,	Count = 49741,	Percentage = 58.4
Class = 4,	Count = 3634,	Percentage = 4.27
```

**Comment by reidjohnson** [comment]
This implementation of SMOTEBoost can be run on multi-class problems, but will only oversample the single most underrepresented class.
